-- Diakonia v2 — schema completo (M1-M10) | gerado automaticamente

-- ENUMS
DO $$ BEGIN CREATE TYPE public.pessoas_sexo_enum AS ENUM ('Masculino', 'Feminino', 'Não informado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.vinculos_familiares_parentesco_enum AS ENUM ('Cônjuge', 'Filho(a)', 'Pai', 'Mãe', 'Irmão(ã)', 'Avô/Avó', 'Outro'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.congregacoes_status_congregacao_enum AS ENUM ('Ativa', 'Inativa', 'Em Plantação', 'Encerrada'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.areas_ministerio_dia_reuniao_enum AS ENUM ('Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.dizimistas_forma_pagamento_enum AS ENUM ('PIX', 'Transferência', 'Dinheiro', 'Débito', 'Crédito', 'Boleto'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.movimentacoes_formais_status_processo_enum AS ENUM ('Iniciado', 'Em Andamento', 'Concluído', 'Cancelado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.cartas_transferencia_status_carta_enum AS ENUM ('Emitida', 'Entregue', 'Vencida', 'Cancelada', 'Recebida'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.documentos_secretaria_status_documento_enum AS ENUM ('Emitido', 'Entregue', 'Vencido', 'Cancelado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.eventos_status_evento_enum AS ENUM ('Planejado', 'Em Andamento', 'Realizado', 'Cancelado', 'Reagendado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.agendamentos_salas_tipo_agendamento_enum AS ENUM ('Evento', 'Reunião', 'Ensaio', 'EBD', 'Outro'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.agendamentos_salas_status_agendamento_enum AS ENUM ('Confirmado', 'Pendente', 'Cancelado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.escalas_voluntarios_status_confirmacao_enum AS ENUM ('Pendente', 'Confirmado', 'Recusado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.comunicados_tipo_comunicado_enum AS ENUM ('Aviso', 'Evento', 'Culto', 'Urgente', 'Boletim', 'Outro'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.comunicados_publico_alvo_enum AS ENUM ('Todos', 'Membros', 'Liderança', 'Voluntários', 'Jovens', 'EBD'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.relatorios_mensais_status_relatorio_enum AS ENUM ('Pendente', 'Em Revisão', 'Concluído'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.pequenos_grupos_dia_reuniao_enum AS ENUM ('Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.pequenos_grupos_tipo_local_enum AS ENUM ('Residência', 'Igreja', 'Online', 'Misto', 'Outro'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.cursos_discipulado_status_curso_enum AS ENUM ('Aberto', 'Em Andamento', 'Concluído', 'Cancelado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.inscricoes_cursos_status_inscricao_enum AS ENUM ('Ativa', 'Concluída', 'Cancelada', 'Desistência'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.novos_convertidos_tipo_decisao_enum AS ENUM ('Conversão', 'Rededição', 'Batismo', 'Outro'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.novos_convertidos_status_acompanhamento_enum AS ENUM ('Em Acompanhamento', 'Batizado', 'Transferido', 'Encerrado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.visitacao_domiciliar_status_visita_enum AS ENUM ('Solicitada', 'Agendada', 'Realizada', 'Cancelada'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.pedidos_oracao_status_oracao_enum AS ENUM ('Em Oração', 'Respondido', 'Arquivado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.situacoes_especiais_status_situacao_enum AS ENUM ('Ativo', 'Em Acompanhamento', 'Encerrado', 'Arquivado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.mentoria_status_mentoria_enum AS ENUM ('Ativo', 'Em Pausa', 'Concluído', 'Encerrado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.projetos_sociais_periodicidade_enum AS ENUM ('Semanal', 'Quinzenal', 'Mensal', 'Bimestral', 'Trimestral', 'Sob Demanda'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.custos_projetos_sociais_tipo_custo_enum AS ENUM ('Alimentação', 'Material', 'Medicamentos', 'Transporte', 'Outro'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.dizimos_historico_forma_pagamento_enum AS ENUM ('PIX', 'Transferência', 'Dinheiro', 'Débito', 'Crédito', 'Boleto'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.repasse_congregacoes_status_repasse_enum AS ENUM ('Pendente', 'Realizado', 'Cancelado', 'Em Análise'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.campanhas_financeiras_status_campanha_enum AS ENUM ('Ativa', 'Encerrada', 'Meta Atingida', 'Cancelada'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.calculos_rpa_status_rpa_enum AS ENUM ('Rascunho', 'Emitido', 'Pago', 'Cancelado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.patrimonio_bens_estado_conservacao_enum AS ENUM ('Ótimo', 'Bom', 'Regular', 'Ruim', 'Inativo'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.manutencoes_tipo_manutencao_enum AS ENUM ('Preventiva', 'Corretiva', 'Emergencial'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.manutencoes_status_manutencao_enum AS ENUM ('Pendente', 'Em Andamento', 'Concluída', 'Cancelada'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.controle_chaves_status_chave_enum AS ENUM ('Disponível', 'Emprestada', 'Extraviada', 'Desativada'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.recursos_humanos_tipo_vinculo_enum AS ENUM ('CLT', 'PJ/Prestador', 'Estágio', 'Voluntário Remunerado', 'Pró-labore'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.recursos_humanos_status_rh_enum AS ENUM ('Ativo', 'Afastado', 'Desligado', 'Em Experiência'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.contratos_rh_status_contrato_enum AS ENUM ('Ativo', 'Vencido', 'Renovado', 'Cancelado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.musica_repertorio_tom_original_enum AS ENUM ('C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.musica_repertorio_tom_preferido_enum AS ENUM ('C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.escalas_louvor_tom_base_enum AS ENUM ('C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.musicas_escala_tom_usado_enum AS ENUM ('C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.emprestimos_biblioteca_status_emprestimo_enum AS ENUM ('Em Curso', 'Devolvido', 'Em Atraso', 'Renovado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.transferencias_inter_congregacao_status_transferencia_enum AS ENUM ('Pendente', 'Em Análise', 'Aprovada', 'Concluída', 'Cancelada'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.planejamento_estrategico_perspectiva_enum AS ENUM ('Financeira', 'Crescimento', 'Processos', 'Aprendizado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.planejamento_estrategico_status_plano_enum AS ENUM ('Em Andamento', 'Concluído', 'Atrasado', 'Cancelado'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.evangelismo_campanhas_tipo_evangelismo_enum AS ENUM ('Porta a Porta', 'Evento', 'Online', 'Telefonema', 'Outro'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.midia_digital_tipo_conteudo_enum AS ENUM ('Culto', 'Devocional', 'Testemunho', 'Evento', 'Informe', 'Outro'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.midia_digital_plataforma_enum AS ENUM ('YouTube', 'Instagram', 'Facebook', 'TikTok', 'WhatsApp', 'Outro'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE public.parceiros_missoes_status_apoio_enum AS ENUM ('Ativo', 'Suspenso', 'Encerrado', 'Em Avaliação'); EXCEPTION WHEN duplicate_object THEN null; END $$;