// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prjoftmlkusbjoeptabp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByam9mdG1sa3VzYmpvZXB0YWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk1ODQyMTQsImV4cCI6MjA5NTE2MDIxNH0.m2U2f7rof_NdykYpv7VapGXoIIau4SisxAO-8VaRX3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
